apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-demo
  labels:
    app: argocd-demo
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: argocd-demo
  template:
    metadata:
      labels:
        app: argocd-demo
    spec:
      containers:
        - name: argocd-demo
          # image: "shariqrizvi/simple-frontend:v9"
          image: paulbouwer/hello-kubernetes:1.5
          ports:
          # - containerPort: 3000
          - containerPort: 8080
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-demo
  labels:
    app: argocd-demo
spec:
  ports:
    - port: 80
      # targetPort: 3000
      targetPort: 8080
      protocol: TCP
  selector:
    app: argocd-demo
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argocd-demo
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/app-root: "/"
spec:
  rules:
    - http:
        paths:
        - path: /
          backend:
            serviceName: argocd-demo
            servicePort: 80
