apiVersion: v1
kind: Service
metadata:
  name: argocd-demo
  labels:
    app: argocd-demo
spec:
  ports:
    - port: 80
      # targetPort: 3000
      targetPort: 4000
      protocol: TCP
  selector:
    app: argocd-demo