apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-demo2
  labels:
    app: argocd-demo2
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: argocd-demo2
  template:
    metadata:
      labels:
        app: argocd-demo2
    spec:
      containers:
      - name: argocd-demo2
        # env:
        #   - name: PORT
        #     valueFrom:
        #       secretKeyRef:
        #         key: PORT
        #         name: test-secrets

        # image: "shariqrizvi/simple-frontend:v9"
        # image: paulbouwer/hello-kubernetes:1.8
        image: kmpartner/nodejs-express-template
        ports:
        # - containerPort: 3000
        - containerPort: 4000
          protocol: TCP
        resources:
          requests:
            memory: "1Mi"
            cpu: "1m"
