apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emojivoto
  namespace: argocd
spec:
  destination:
    namespace: emojivoto
    server: https://kubernetes.default.svc
  project: demo2
  source:
    # path: gitops/resources/emojivoto
    path: app-of-apps/gitops/resources/emojivoto
    # repoURL: git://git-server.scm:9418/linkerd-examples.git
    repoURL: git://git-server.scm:9418/argo-demo.git
